### ISSUE TITLE
Distribution via conda-forge

### ISSUE THREAD

**Issue by ericmjl** [vinayak-mehta/nbcommands#12]
@vinayak-mehta I'm also wondering whether you'd like to consider distributing the package through conda-forge? 

If you are interested in doing so, but don't have the bandwidth to begin, I'm happy to kickstart the process for you. Maintenance post-deployment to conda-forge is very easy, as you just have to take care of the PyPI version, and a bot will do what's needed to update on conda-forge and ping you (and me, I'm happy to look out for the conda-forge package updates too).

Please let me know!

**Comment by vinayak-mehta** [comment]
I've distributed a package through conda-forge before :) I'll create a release there today!

**Comment by vinayak-mehta** [comment]
Raised a PR: https://github.com/conda-forge/staged-recipes/pull/10049

**Comment by vinayak-mehta** [comment]
The package should be available through conda-forge shortly :)
